version: '3.8'

services:
  traillink-backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    env_file:
      - backend/.env
    volumes:
      - ./backend/logs:/app/logs
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - traillink-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=traillink
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - traillink-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - traillink-backend
    restart: unless-stopped
    networks:
      - traillink-network

volumes:
  mongodb_data:

networks:
  traillink-network:
    driver: bridge